name: Check brach build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: read

    steps:
      - uses: actions/checkout@v4

      - name: Fetch main
        run: git fetch origin main

      - name: merge PR locally
        run: |
          git checkout main
          git merge --no-commit --no-ff ${{ github.event.pull_request.head.ref }}

      - name: Run tests
        run: ./test.sh
