name: Check branch build

on: 
  pull_request:
    branches:
      - main
    

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: 
        contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Fetch main
        run: |
          git fetch origin main
          git fetch origin ${{ github.event.pull_request.head.ref }}

      - name: merge PR locally
        run: |
          git checkout main
          git merge --no-commit --no-ff origin/${{ github.event.pull_request.head.ref }}

      - name: Run tests
        run: ./test.sh
